function test_write_edf_string_labels()
%TEST_WRITE_EDF_STRING_LABELS  string-typed header fields survive a write.
%
%   Regression for the silent blank-label bug: signal headers built with
%   MATLAB string objects — e.g.
%       'signal_labels', num2cell([string(1:64), "CA"])
%   — hit the MEX's get_string_field, which requires mxChar and wrote an
%   EMPTY field for anything else. Every channel label in the output EDF
%   was blank, with no diagnostic. write_EDF now normalizes text fields
%   to char at its entry, covering both the MEX and pure-MATLAB backends.
%
%       cd tests; test_write_edf_string_labels

n = 5;
labels = [string(1:n-1), "CA"];   % the failing construction, small
want = arrayfun(@char, labels, 'UniformOutput', false);

signal_hdr = struct( ...
    'signal_labels',      num2cell(labels), ...
    'transducer_type',    "", ...
    'physical_dimension', "uV", ...
    'physical_min',       -3200, ...
    'physical_max',        3200, ...
    'digital_min',        -32768, ...
    'digital_max',         32767, ...
    'prefiltering',       "", ...
    'samples_in_record',   200, ...
    'sampling_frequency',  200);

header = struct( ...
    'edf_ver', "0", ...
    'patient_id', "X X X X", ...
    'local_rec_id', "Startdate X X X X", ...
    'recording_startdate', '01.01.20', ...
    'recording_starttime', '12.00.00', ...
    'num_header_bytes', 256 + 256 * n, ...
    'num_data_records', 2, ...
    'data_record_duration', 1, ...
    'num_signals', n);

sc = arrayfun(@(i) sin(2 * pi * (1:400) / 100) * 100, 1:n, 'UniformOutput', false);

tmp = tempname();
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, 's'));

for force_matlab = [false, true]
    out = fullfile(tmp, sprintf('string_labels_%d.edf', force_matlab));
    write_EDF(out, header, signal_hdr, sc, 'forceMATLAB', force_matlab);
    [~, sh_back] = read_EDF(out);
    got = strtrim({sh_back.signal_labels});
    assert(isequal(got, want), ...
        'labels did not survive (forceMATLAB=%d): got %s', ...
        force_matlab, strjoin(got, ','));
end

fprintf('test_write_edf_string_labels: all assertions passed\n');
end
